development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:298dbfdb060ee60ec5889dfb41feaa80@tarpon.redistogo.com:11202/
  channel_prefix: we_survivin_backend_production
